/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_lojaw_jni_NativeOverlayRenderer */

#ifndef _Included_de_lojaw_jni_NativeOverlayRenderer
#define _Included_de_lojaw_jni_NativeOverlayRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_lojaw_jni_NativeOverlayRenderer
 * Method:    initOverlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_lojaw_jni_NativeOverlayRenderer_initOverlay
  (JNIEnv *, jclass);

/*
 * Class:     de_lojaw_jni_NativeOverlayRenderer
 * Method:    renderOverlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_lojaw_jni_NativeOverlayRenderer_renderOverlay
  (JNIEnv *, jclass);

/*
 * Class:     de_lojaw_jni_NativeOverlayRenderer
 * Method:    destroyOverlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_lojaw_jni_NativeOverlayRenderer_destroyOverlay
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
